import Head from "next/head";
import { TranslateLanguageForm } from "../src/components/translate-language-form";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Translate it!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Translate it!</h1>
        <TranslateLanguageForm />
      </main>
    </div>
  );
}
